### ISSUE TITLE
原博客不能访问

### ISSUE THREAD

**Issue by hipboi** [Icenowy/icenowy.github.io#1]
把域名指向了github，原博客不能访问了。

**Comment by Icenowy** [comment]
2016年10月26日 14:20于 Tom Cubie notifications@github.com写道：

> 把域名指向了github，原博客不能访问了。

反正原博客也没有东西。（

**Comment by hipboi** [comment]
对很多文章感兴趣，麻烦给个备份链接。

**Comment by Icenowy** [comment]
2016年10月28日 10:44于 Tom Cubie notifications@github.com写道：

> 对很多文章感兴趣，麻烦给个备份链接。

然而原来博客上一篇有意义的文章都没有 😂
